title = "Red Hat Brasil | Workshops | Test Drives | Demos"
baseURL = "https://redhatbr.io/"
theme = "redhatgov"
languageCode = "en-us"
metaDataFormat = "yaml"

[params]
    description = "Tried. Tested. Trusted."

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100
